dashboard_pp:
    resource: "@DashboardPpBundle/Resources/config/routing.yml"
    prefix:   /

dashboardshells:
    resource: "@DashboardshellsBundle/Resources/config/routing.yml"
    prefix:   /


dashboard_restfull:
    resource: "@DashboardRestfullBundle/Resources/config/routing.yml"
    prefix:   /

dashboard_user:
    resource: "@DashboardUserBundle/Resources/config/routing.yml"
    prefix:   /

dashboard_admin:
    resource: "@DashboardAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


pageNotFound:
    path:  /{path}
    defaults: { _controller: DashboardAdminBundle:Error:Error, path: '' }
    requirements:
        path: .*